### PR TITLE
Allow pynbody to infer AREPO HDF5 units

### PR DESCRIPTION
**Pull request by bwkeller**
AREPO has changed where some of the unit information is stored in a Gadget-HDF5 file.  This change should let cosmo/non-cosmo AREPO snapshots to get read with units properly loaded, rather than always falling back to the gadget cosmo units.

### CODE REVIEW

**Comment by apontzen** [comment]
Is there any chance of getting a regression test based on a small test file?

**Comment by bwkeller** [comment]
Sure, would it be a good idea just to base it off of the gadgethdf test that currently is in the nose tests?

**Comment by apontzen** [comment]
Sure, that sounds good!

**Comment by bwkeller** [comment]
I've added an extra set of nose tests, just simple checks to make sure the new AREPO units reading is working for both cosmological and non-cosmological zooms.  Since the units are all I really changed, I didn't duplicate the tests that already exist for gadget and gadget HDF snapshots.

**Comment by bwkeller** [comment]
Oh, the tests are failing because the testdata is missing my new test files.  I've put up the ones we need for the tests here: https://project2501.ca/arepo.tar.gz

**Comment by apontzen** [comment]
Thanks @bwkeller - I added the files to the testdata tar but unfortunately the tests still fail (e.g. https://travis-ci.org/github/pynbody/pynbody/jobs/733354558) - now due to a problem with using units in `assert_almost_equal`. Could you check?

**Pull request closed without merging**
