### PR TITLE
Using custom CMDs

### PR DESCRIPTION
**Pull request by apontzen**
…ript for generating such a file

### CODE REVIEW

**Comment by elehcim** [comment]
Hello Andrew, thanks for this, especially the script in the comment will be quite useful for me. One thing: why not passing the `cmdlum_file` path directly to `calc_mags` function (with default for example to `os.path.join(os.path.dirname(__file__), "cmdlum.npz")`)? I think it would avoid globals and make it explicit which file you are using. Also one doesn't need to remember to call a function to revert it back.

**Comment by apontzen** [comment]
Thanks... the main reason for this is so that people can use the ‘derived arrays’ which automatically calculate the magnitudes. However I agree it would be useful to have also an option to pass the path if directly calling the function. I’ll add this before merging.

**Comment by apontzen** [comment]
@elehcim would be interested to check this update addresses your question

**Comment by elehcim** [comment]
> Thanks... the main reason for this is so that people can use the ‘derived arrays’ which automatically calculate the magnitudes. However I agree it would be useful to have also an option to pass the path if directly calling the function. I’ll add this before merging.

Oh, I see why you had to use globals. Thanks for the modifications.

**Pull request merged**
