### PR TITLE
Calculate Fourier modes without binning

### PR DESCRIPTION
**Pull request by jakobherpich**
I changed the method to do the Fourier analysis on non-axisymmetric disk perturbations to avoid loss of information through binning and, thus, increase accuracy. The calculation is based on the method of Quillen et al. 2011 (http://adsabs.harvard.edu/abs/2011MNRAS.417..762Q).

It should also be computationally more efficient because it avoids all the binning and histogram calculations. 

This also fixes issue #375.

I tested the method with multiple galaxies.

### CODE REVIEW

**Comment by rokroskar** [comment]
actually looks like the binning here was changed a year ago by @apontzen when the 'pattern speed estimation" was added (8fcb42a0). So not sure why the bins are the way they are but I agree that it looks wrong. 

The initial implementation (see c822636) did not use binning. Using the binning speeds up the calculation a lot -- with the binning you only loop through the particles once, whereas without the binning you loop through all the particles for each fourier component. If you have a lot of particles that's a lot of iterations and if you are doing it for just one output you might not care, but if you need to run this for 1000 outputs with 10M particles each then it starts to matter. I found that using ~100 bins or so in phi is sufficient to give nearly identical results to using particles -- I think if I was constructing maps of fourier components I may have used more bins to make it look smoother.

**Comment by jakobherpich** [comment]
I did not realize what @rokroskar said and it makes sense.

I will then change the binning to solve issue #375 and close this PR.

**Comment by apontzen** [comment]
Oh dear, I don't remember doing this. We should add a unit test to make sure it doesn't happen again.

**Comment by rokroskar** [comment]
indeed, a unit test here is sorely lacking

btw, @apontzen did someone request to have the instantaneous pattern speed estimate put in here? Any idea if it matches well with an actual pattern speed measurement?

**Comment by apontzen** [comment]
I think I was just fooling around. It was not used for any science that I know of. Sorry for breaking existing code!

**Comment by jakobherpich** [comment]
@rokroskar No, the pattern speed estimation does not work. One of our students tried to use it and got crazy results.

I'm going to create a different PR that actually implements calculating spectrographs based on multiple snapshots.

**Comment by apontzen** [comment]
we should probably remove the pattern speed estimation in that case, to prevent further confusion... unless the reason it doesn't work is because of the binning error.

**Comment by jakobherpich** [comment]
@apontzen I will test this and if it still fails remove this feature.

**Pull request closed without merging**
