### PR TITLE
Merger tree

### PR DESCRIPTION
**Pull request by TobiBu**
This is a commit to handle merger tree files and plot merger trees with pynbody.
I created a file "tree.py" containing classes to handle files created with the AHF merger tree tool and to read in merger trees and halo properties from the AHF halo catalogue.
There is also an abstract class to implement more merger tree tool like e.g. the rockstar consistent-tree tool.

This commit is still laking a written documentation.

### CODE REVIEW

**Comment by apontzen** [comment]
Could you add an example so I can test this in real-world use? Thanks!

**Comment by TobiBu** [comment]
You mean just a piece of code showing how it works?
I also thought about writing a short tutorial if it gets merged.

**Comment by apontzen** [comment]
Yes a piece of code or even better a tutorial. It's hard at the moment to verify what it does. Thanks!

**Comment by TobiBu** [comment]
Hi,
I created a jupiter notebook explaining the basic functions. If you have AHF installed and the merger tree tool configure (in the subfolder analysis in the AHF folder) you should be able to run the notebook on one of your galaxies. Please let me know if everything works for you. On my laptop it works with python3 and on the server with python2.7. So there should be no problems. 

[merger_tree_tutorial.ipynb.zip](https://github.com/pynbody/pynbody/files/1556469/merger_tree_tutorial.ipynb.zip)

**Comment by apontzen** [comment]
Sorry for long delay - I think given where tangos has got to, this probably doesn't belong in pynbody. Do you agree or should some aspect of this functionality still be merged?

**Comment by TobiBu** [comment]
No, I think the tangos implementation should be sufficient.
The only thing which still might be interesting is the automatic run of the AHF MergerTree code in case the mtree files are not present...

**Comment by apontzen** [comment]
Sounds like it could be a helpful script but again probably belonging to tangos rather than pynbody

**Pull request closed without merging**
