### PR TITLE
SPH curl and divergence 

### PR DESCRIPTION
**Pull request by elehcim**
I added curl and divergence in the SPH module.
I added the "derived quantity" functions for velocity curl (`v_curl` or `vorticity`) and velocity divergence `v_div`.

- [x] ~~Stil WIP, need tests~~. Comments and corrections welcome.
- [x] ~~In case #601 is merged, I'll rebase~~. Rebased

### CODE REVIEW

**Comment by elehcim** [comment]
I coded the divergence and the curl using the first order div and curl approximation as found in eq. (79) of [Price 2012](https://www.sciencedirect.com/science/article/pii/S0021999110006753) (with \phi_a=\phi_b=1).
I double checked my code and as far as I can tell, I'm doing the same steps as [plonk](https://github.com/dmentipl/plonk/blob/a304aa6ef7eb237158feca61ab3bad4a9dee17a9/plonk/analysis/sph.py#L316) (btw, also a very nice piece of software! They write that the SPH summation is still experimental).
I don't have a proven use case to check the results. If anybody has an already computed dataset of curl and/or divergence it would be useful.
In case not, I'd add a test with the result that the code is producing now.

**Comment by elehcim** [comment]
I've found a bug in the kernel gradient computation. It should be ok now.
Now I can reproduce the vorticity of the Gresho vortex. See code and image below

```python
import pynbody
import numpy as np

import matplotlib.pyplot as plt

def gresho_analytical_vorticity(r):
    c1 = np.where(r<0.2)
    c2 = np.where(np.logical_and(0.2<=r, r<0.4))
    omega_z = np.zeros_like(r)
    omega_z[c1] = 10
    omega_z[c2] = 2/r[c2] - 10
    return omega_z

def gresho_vortex(N_side=1000):
    snap = pynbody.snapshot.new(gas=N_side**2)
    side = np.linspace(-0.5, 0.5, N_side)
    x,y = np.meshgrid(side,side)
    z = np.zeros_like(x).ravel()
    pos = np.vstack([x.ravel(),y.ravel(),z.ravel()]).T
    snap['pos'] = pynbody.array.SimArray(pos, units='m')
    r = np.linalg.norm(pos, axis=1)
    phi = np.arctan2(pos[:,1],pos[:,0])
    vel = np.zeros_like(pos)
    c1 = np.where(r<0.2)
    c2 = np.where(np.logical_and(0.2<=r, r<0.4))
    vel[c1,0] =   5 * r[c1]  * -np.sin(phi[c1])
    vel[c1,1] =   5 * r[c1]  *  np.cos(phi[c1])
    vel[c2,0] = (2-5* r[c2]) * -np.sin(phi[c2])
    vel[c2,1] = (2-5* r[c2]) *  np.cos(phi[c2])
    snap['vel'] = pynbody.array.SimArray(vel, units='m s**-1')

    # Compute the particle mass producing a density of 1: initialize
    snap['mass'] = pynbody.array.SimArray(np.ones_like(z), units='kg')
    cuboid = pynbody.snapshot.filt.Cuboid(-0.25)
    desired_rho = 1
    # average mass
    avg_mass = desired_rho/np.mean(snap[cuboid]['rho']).view(np.ndarray)
    snap['rho_old'] = snap['rho']
    del snap['rho']
    # set mass
    snap['mass'] = pynbody.array.SimArray(np.ones_like(z)*avg_mass, units='kg')
    return snap

snap = gresho_vortex(N_side=1000)

fig, ((ax_vphi, ax_quiver), (ax_vort_profile, ax_vort_map)) = plt.subplots(ncols=2, nrows=2)

snap['vorticity_z'] = snap['vorticity'][:,2]

ax_quiver.set_title('Velocity field')
pynbody.plot.sph.velocity_image(snap, width=1, subplot=ax_quiver,
                                vmin=0, vmax=2, log=False,
                                show_cbar=False, quiverkey=False)
im_v = pynbody.plot.image(snap, qty='vorticity_z', width=1, subplot=ax_vort_map,
                          log=False, show_cbar=True)

ax_vort_map.set_title(r'$\omega_z$ distribution')

p = pynbody.analysis.profile.Profile(snap, ndim=2, type='equaln')

ax_vphi.plot(p['rbins'], p['vphi'])
ax_vphi.set_xlabel(r'r')
ax_vphi.set_ylabel(r'$v_\phi$')

r = np.linspace(0, 0.4, 100)
omega_z = gresho_analytical_vorticity(r)
ax_vort_profile.plot(r, omega_z, label='true', ls='--')
ax_vort_profile.plot(p['rbins'], p['vorticity_z'], label='measured')
ax_vort_profile.set_ylim(-6, 11)
ax_vort_profile.set_xlabel(r'r')
ax_vort_profile.set_ylabel(r'$\omega_z$')
ax_vort_profile.legend()
```

Selection_103

**Comment by elehcim** [comment]
I tried a similar exercise with divergence. I built a simple divergent velocity field. 

The results are consistent with the expected value.

```python
import pynbody
import numpy as np
import matplotlib.pyplot as plt

def diverging_field(N_side=1000):
    snap = pynbody.snapshot.new(gas=N_side**2)
    side = np.linspace(-0.5, 0.5, N_side)
    x,y = np.meshgrid(side,side)
    z = np.zeros_like(x).ravel()
    pos = np.vstack([x.ravel(),y.ravel(),z.ravel()]).T
    snap['pos'] = pynbody.array.SimArray(pos, units='m')
    r = np.linalg.norm(pos, axis=1)
    phi = np.arctan2(pos[:,1],pos[:,0])
    vel = np.zeros_like(pos)
    vel[:,0] =   5 * r  * np.cos(phi)
    vel[:,1] =   5 * r  * np.sin(phi)
    snap['vel'] = pynbody.array.SimArray(vel, units='m s**-1')
    snap['mass'] = pynbody.array.SimArray(np.ones_like(z)*1e-5, units='kg')
    return snap

snap = diverging_field(N_side=100)

fig, ((ax_vr, ax_quiver), (ax_div_profile, ax_div_map)) = plt.subplots(ncols=2, nrows=2)

ax_quiver.set_title('Velocity field')
pynbody.plot.sph.velocity_image(snap, width=1, subplot=ax_quiver,
                                vmin=0, vmax=2, log=False, #mode='stream',
                                show_cbar=False, quiverkey=False)
im_v = pynbody.plot.image(snap, qty='v_div', width=1, subplot=ax_div_map,
                          log=False, show_cbar=True)

ax_div_map.set_title(r'$\nabla \cdot \vec v$ distribution')

p = pynbody.analysis.profile.Profile(snap, ndim=2, type='equaln')#, weight_by='ones')

ax_vr.plot(p['rbins'], p['vr'])
ax_vr.text(0.1,2,r'$v_r = 5 \cdot r$')
ax_vr.set_xlabel(r'r')
ax_vr.set_ylabel(r'$v_r$')

r = np.linspace(0, 0.5, 100)
ax_div_profile.plot(r, np.ones_like(r)*10, label='true', ls='--')
ax_div_profile.plot(p['rbins'], p['v_div'], label='measured', ls=":")
# ax_div_profile.set_ylim(-6, 11)
ax_div_profile.set_xlim(0, 0.5)
ax_div_profile.set_xlabel(r'r')
ax_div_profile.set_ylabel(r'$\nabla \cdot \vec v$')
ax_div_profile.legend()
```
Selection_104

**Comment by apontzen** [comment]
It looks great - I can take a quick look through but it seems like you already checked this very carefully.

Is there anything you think still needs to be checked, or is it ready to merge?

**Comment by elehcim** [comment]
> It looks great - I can take a quick look through but it seems like you already checked this very carefully.

Thanks for taking a quick look.

> Is there anything you think still needs to be checked, or is it ready to merge?

I think it's ready.

**Comment by apontzen** [comment]
Thanks!

**Pull request merged**
