### PR TITLE
Phase diagram plot that handles gasoline and ChaNGa superbubble outputs automatically

### PR DESCRIPTION
**Pull request by bwkeller**
I stupidly changed the names of some of the variables output when superbubble is enabled in ChaNGa relative to their original implementation in gasoline.  The code I wrote in `pynbody.plot.gas.rho_T` to handle this was written forgetting this, so I've fixed that now.  The two relevant auxiliary files are:

- `MassHot` in gasoline is `massHot` in ChaNGa
- `Tinc` in gasoline is `tempEff` in ChaNGa.

### CODE REVIEW

**Comment by apontzen** [comment]
Should this perhaps be handled at the level of the name mappers rather than in a single analysis routine?

**Comment by bwkeller** [comment]
I think that does make sense, but I must confess I'm not super familiar with the name mapper architecture.  Would this just consist of a change to default_config.ini?

**Comment by apontzen** [comment]
Yes that's right, just add the appropriate lines there

**Comment by bwkeller** [comment]
I've made the change to use the name mapper instead of hand-fixing `Tinc` and `MassHot`.  I needed to change the tipsy snapshot reader, as it previously had no support for name mapping.  In the interest of not breaking anyone's analysis scripts, you will now have loadable keys for both the gasoline and ChaNGa naming conventions for the two phase properties.

**Pull request merged**
