### PR TITLE
Subfind merge

### PR DESCRIPTION
**Pull request by rokroskar**
new PR for the merge of pull request #177

### CODE REVIEW

**Comment by rokroskar** [comment]
not sure why the travis build fails with all the import errors -- can't reproduce this locally

**Comment by apontzen** [comment]
At the moment I also fail to run the unit tests on my local machine:

```
...................../Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/gadget.py:461: RuntimeWarning: Run out of block names in the config file. Using fallbacks: UNK*
  "Run out of block names in the config file. Using fallbacks: UNK*", RuntimeWarning)
.......Epynbody.analysis.profile : Profile v_circ -- this routine assumes the disk is in the x-y plane
.........../Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/ramses.py:272: RuntimeWarning: More hydro variables (7) are in this RAMSES dump than are defined in config.ini (6)
  nvar_file, nvar), RuntimeWarning)
/Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/ramses.py:272: RuntimeWarning: More hydro variables (7) are in this RAMSES dump than are defined in config.ini (6)
  nvar_file, nvar), RuntimeWarning)
/Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/ramses.py:272: RuntimeWarning: More hydro variables (7) are in this RAMSES dump than are defined in config.ini (6)
  nvar_file, nvar), RuntimeWarning)
/Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/ramses.py:272: RuntimeWarning: More hydro variables (7) are in this RAMSES dump than are defined in config.ini (6)
  nvar_file, nvar), RuntimeWarning)
............................../Users/app/anaconda/lib/python2.7/site-packages/pynbody/simdict.py:92: RuntimeWarning: Assuming default value for property 'a'=1.00e+00
  name, value), RuntimeWarning)
../Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/tipsy.py:1496: RuntimeWarning: Paramfile suggests time is cosmological, but header values are not sensible in this context.
  "Paramfile suggests time is cosmological, but header values are not sensible in this context.", RuntimeWarning)
..........................
======================================================================
ERROR: test suite for <module 'gadgethdf_test' from '/Users/app/Science/pynbody/nose/gadgethdf_test.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/app/anaconda/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/app/anaconda/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/app/anaconda/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/app/anaconda/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/app/Science/pynbody/nose/gadgethdf_test.py", line 7, in setup
    snap = pynbody.load('testdata/Test_NOSN_NOZCOOL_L010N0128/data/snapshot_103/snap_103.hdf5')
  File "/Users/app/anaconda/lib/python2.7/site-packages/pynbody/__init__.py", line 169, in load
    return c(filename, *args, **kwargs)
  File "/Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/gadgethdf.py", line 174, in __init__
    self._decorate()
  File "/Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/__init__.py", line 1549, in _decorate
    fn(self)
  File "/Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/gadgethdf.py", line 459, in do_units
    for fac in GadgetHDFSnap._get_cosmo_factors(sim._hdf[0],'Coordinates') : dist_unit *= fac
  File "/Users/app/anaconda/lib/python2.7/site-packages/pynbody/snapshot/gadgethdf.py", line 273, in _get_cosmo_factors
    return units.a**a_exp, units.h**h_exp
  File "/Users/app/anaconda/lib/python2.7/site-packages/pynbody/units.py", line 144, in __pow__
    raise ValueError, "Units can only be raised to integer or fractional powers"
ValueError: Units can only be raised to integer or fractional powers
-------------------- >> begin captured logging << --------------------
```

**Comment by rokroskar** [comment]
yes I saw the same -- this didn't fail before I merged in the current master

**Comment by rokroskar** [comment]
@apontzen any thoughts on the failing unit test? I forget how gadget's unit system works but my understanding was that you simply need to use the powers of `a` supplied in the parameter file. @astroduff any comments?

**Comment by astroduff** [comment]
So each parameter has 'a' and 'h' dependencies given as an attribute in the hdf5 dataset
making it easy to load them... I've added a new, cleaner, unit loading system for the various
quantities in the HDF5 format but noticed that it goes wrong if you try to use "physical_units" 
command which might be a clue? 

e.g.

In [1]: import pynbody as pn

In [2]: s = pn.load('~/pynbody_rokfork/nose/testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103')
Loading using backend <class 'pynbody.gadgethdf.SubFindHDFSnap'>

In [3]: h  = s.halos()

In [4]: h[0].g['StarFormationRate']
Out[4]: 
SimArray([ 0.0490498 ,  0.06204738,  0.07794842, ...,  0.        ,  0.        ,  0.        ], dtype=float32, 'Msol yr**-1.0')

In [5]: s.physical_units()
SimSnap: converting StarFormationRate units from Msol yr**-1.0 to km Msol kpc**-1.0 s**-1.0

In [6]: h[0].g['StarFormationRate']
Out[6]: 
SimArray([ 47961576.,  60670800.,  76219056., ...,         0.,         0.,               0.], dtype=float32, 'km Msol kpc**-1.0 s**-1.0')

Thoughts?

**Comment by apontzen** [comment]
The units module is not built to accept floats as powers, only rationals and integers...

**Comment by astroduff** [comment]
I've tried catching this in the code by using fractions, but still no luck.

For example, one unit that gets load in halo.py is the Mass where

hexp = -1.0

and the following command in the code for halo.py 

print (units.h)**util.fractions.Fraction(hexp)

gives an error of:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fractions.pyc in __new__(cls, numerator, denominator)
    146 
    147             else:
--> 148                 raise TypeError("argument should be a string "
    149                                 "or a Rational instance")
    150 

TypeError: argument should be a string or a Rational instance

while doing the same in the command line gives

In [5]: hexp=-1.0

In [6]: pn.units.h**pn.util.fractions.Fraction(hexp)
Out[6]: Unit("h**-1")


I'm not sure what to do about this as I thought fractions was the preferred method?

Cheers
Alan

**Comment by apontzen** [comment]
Have you tried `(units.h)**util.fractions.Fraction(float(hexp))`? Seems like it's expecting a native float.

I would also use `limit_denominator()` i.e. something like `(units.h)**util.fractions.Fraction(float(hexp)).limit_denominator()` (see here https://docs.python.org/2/library/fractions.html)

**Comment by astroduff** [comment]
Hey Andrew

Thanks for that, I've made those changes however I'm still seeing strange behaviour with physical_units()

In [1]: import pynbody as pn

In [2]: s = pn.load('/Users/aduffy/Code/Python/pynbody_rokfork/nose/testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103')
Loading using backend <class 'pynbody.gadgethdf.SubFindHDFSnap'>

In [3]: s.g['StarFormationRate']
Out[3]: 
SimArray([ 0.0490498 ,  0.06204738,  0.07794842, ...,  0.        ,        0.        ,  0.        ], dtype=float32, 'Msol yr**-1')

In [4]: h = s.halos()

In [5]: h[0].g['StarFormationRate']
Out[5]: 
SimArray([ 0.0490498 ,  0.06204738,  0.07794842, ...,  0.        ,        0.        ,  0.        ], dtype=float32, 'Msol yr**-1')

In [6]: s.physical_units()
SimSnap: converting StarFormationRate units from Msol yr**-1 to km Msol kpc**-1 s**-1

In [7]: s.g['StarFormationRate']
Out[7]: 
SimArray([ 47961576.,  60670800.,  76219056., ...,         0.,         0.,              0.], dtype=float32, 'km Msol kpc**-1 s**-1')

In [8]: h[0].g['StarFormationRate']
Out[8]: 
SimArray([ 47961576.,  60670800.,  76219056., ...,         0.,         0.,              0.], dtype=float32, 'km Msol kpc**-1 s**-1')

Any idea why it doesn't recognise Msol yr**-1 as the physical_units and instead drops in Msol s**-1 km / kpc ??

Cheers
Alan

**Comment by apontzen** [comment]
Yes, this is expected behaviour as physical_units projects all units into a set consistent with Msol, kpc, and km/s. I agree it's a little unhelpful in this case but fixing it would require adding yr to that set, which would then require an algorithm to choose 'the most natural' for each case, as the choice becomes ambiguous.

You can run physical_units with your own choice, however, so if you prefer you could use Msol, kpc and yr. But then your velocities would be in kpc yr^-1 etc...

**Comment by astroduff** [comment]
Ok cool thanks for that, just happy to learn it's not something I've done to the code..!

Cheers
Alan 

=============================
Dr Alan Duffy
Research Fellow
Centre for Astrophysics and Supercomputing
Swinburne University of Technology
Vic 3122, Australia

Email: mail@alanrduffy.com
Web: www.alanrduffy.com
Twitter: @astroduff
=============================

**Comment by rokroskar** [comment]
hey @astroduff I get a unit test failing at https://github.com/pynbody/pynbody/blob/subfind_merge/pynbody/snapshot/gadgethdf.py#L384 -- it seems to be because gadgethdf_test.py `test_standard_arrays()` tries to access `subfind.gas['u']` which doesn't seem to exist: 
```
  (Pdb) self._get_hdf_dataset(hdf0[self._my_type_map[famx][0]], translated_name)
  *** KeyError: "Unable to open object (Object 'u' doesn't exist)" 
```

is this a problem with the test or the dataset or the `_load_array` method?

**Comment by rokroskar** [comment]
@astroduff: btw, this is *with* the changes that you pushed to my fork -- from now on, please make changes to this branch only since I have already done all the merging and once the errors are gone we can merge into master directly.

**Comment by rokroskar** [comment]
@apontzen -- I don't understand these travis build failures -- it seems to not be able to import `backcompat`??

**Comment by apontzen** [comment]
I see the same error when I try to run this branch's unit tests on my machine.  Interestingly when I try to import pynbody from an interpreter I still get an ImportError but this time from the `gadget` module. 

I don't have time to debug this right now but I dumped a (verbose) session here in case it helps

https://gist.github.com/apontzen/c0cc119fc1e7018a3f8a

**Comment by rokroskar** [comment]
there seems to be some bizarre dependency problem -- I have two miniconda profiles, one is my "regular" one, and the other is exactly as the one specified in the travis build for python 2.7 and numpy 1.8.1. The former works fine, even if I use exactly the same packages as in the latter, while the latter fails in the same way as in the travis builds. If I run the nosetests, I get the same backcompat import problem. If I run from the shell, it fails to import gadget, like @apontzen found.

**Comment by rokroskar** [comment]
the unit tests are now failing for Python 3.X due to print statements and the like

**Comment by apontzen** [comment]
2to3 should catch those...


On 15 May 2015, at 17:41, Rok Ro?kar <notifications@github.com<mailto:notifications@github.com>> wrote:


the unit tests are now failing for Python 3.X due to print statements and the like

-

**Comment by astroduff** [comment]
Hi Rok

It's not giving me any troubles? 


In [4]: s = pn.load('/Users/aduffy/Code/Python/pynbody_rokfork/nose/testdata/Test_NOSN_NOZCOOL_L010N0128/data/subhalos_103/subhalo_103')
Loading using backend <class 'pynbody.gadgethdf.SubFindHDFSnap'>

In [5]: h = s.halos()

In [6]: h[0].g['u']
SimSnap: deriving array u
<type 'numpy.float32'>
<type 'numpy.float32'>
SimSnap: deriving array mu
SimSnap: deriving array HI
Loading /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pynbody/analysis/h1.hdf5
<type 'numpy.float32'>
<type 'numpy.float32'>
Interpolating hi values
SimSnap: deriving array hydrogen
<type 'numpy.float32'>
<type 'numpy.float32'>
SimSnap: deriving array HII
SimSnap: deriving array HeI
Loading /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pynbody/analysis/ionfracs.npz
Out[6]: 
SimArray([   314418.57123941,    310363.08924788,    321199.27833686, ...,
        15869494.06779661,   9886323.94067797,  18069563.13559322], 'k K m_p**-1')


Can I just check exactly what branch you want me to push too to prevent me mucking up the set up / merging plan please?

Cheers
Alan

**Comment by rokroskar** [comment]
hey @astroduff you should commit to https://github.com/pynbody/pynbody/tree/subfind_merge

**Comment by apontzen** [comment]
Hi @astroduff, @rokroskar. What is the status of this? We really need to get this merged in as it is delaying other work.

**Comment by rokroskar** [comment]
@apontzen: the travis builds seem to be passing so this can be merged I think 
@astroduff: please open an issue feature request and put the bits that are still missing in there, e.g. efficient calculation of aggregate (sub)halo properties

**Comment by astroduff** [comment]
Hey all, 

Sorry for the silence on this, I hadn't realised I was holding things up. This seems fine
and I'll add a wish list Rok as suggested...

Thanks for all the help gang!

Cheers
Alan

**Comment by apontzen** [comment]
Thanks both! Great to get this merged in.

**Comment by rokroskar** [comment]
whew, finally... I guess all the checkboxes for v0.3 are ticked now...

**Comment by astroduff** [comment]
Thanks for the help all, definitely only possible thanks to you heroes
and will hopefully make it easier to use these datasets more widely..!

Cheers
Alan

**Pull request merged**
