### PR TITLE
Fix family mapping for AHF halos

### PR DESCRIPTION
**Pull request by Martin-Rey**
Hi @apontzen and @cphyc,

I finally got to the bottom of #691, which I have now corrected in this PR. The summary is: AHF is typically run on snapshots that have DM+star+gas and nothing else. New Ramses snapshots (and maybe others) have extra families (BHs, tracers, ...), adding a lot of additional particles that AHF is unaware of. When reading the AHF membership IDs on disc, one then need to remap them to their correct family slices, taking into the extra particles into account.  

They are two open points for me in this
1. I am not sure whether the explicit type check on `RamsesSnap` and `NchildaSnap` are necessary. These seem to have been introduced to deal with the fact that sometimes, gas needs to be the first family, whereas in some others, it's the last. I feel like `self.base._get_family_slice` should deal with this naturally without having to know the snapshot type. I'm happy to try removing these type checks, but I don't think they are tested explicitly, and don't want to break others' code without knowing.
2. I constructed a test based on an EDGE2 snapshot, to help me isolate the issue and convince myself it is fixed. The testdata is currently missing and failing the PR, but is also a fairly beefy production output.  I would prefer to have a more portable test snapshot, but would need an output with the new Ramses format and particle tracers that is small and complete to be able to run AHF on it (unlike the test snapshot which is missing CPU files). What do you think is the best way forward for this?

Hope that helps,
Martin

### CODE REVIEW

**Comment by apontzen** [comment]
I suggest merging master into here to fix the failing tests

**Comment by Martin-Rey** [comment]
I would be happy to do this, but we also need to update the testdata to add an additional snapshot to fix the tests. It's unclear to me what the best way forward for this is (Point 2 above).

**Comment by apontzen** [comment]
I suggest merging anyway, so that we can see that it's only those tests missing data which are failing.

What size are we talking about? Is it truly impossible to hack it to work with missing CPUs?

**Comment by Martin-Rey** [comment]
That should be the case now, let m play around with the formats and outputs to see how I can compact them.

**Comment by Martin-Rey** [comment]
Ok I have managed to reduce the target file to 1.2G and to produce an AHF output for it. I need a decent amount of particles to produce a halo catalogue that makes sense and that be can interpreted and tested.

I haven't managed to convert and/or run AHF on the existing snapshots, as the only output with the new format is non-cosmological and returns an empty halo catalogue.

Let me know if that works and I'll send you a gzip.

**Comment by Martin-Rey** [comment]
Hi Andrew, as far as I can tell, the tests are now failing solely because of the lack of additional test data.

Let me know if the above addition sounds reasonable to you.

**Comment by apontzen** [comment]
Please do point me to the new dataset you created for testing. I am concerned at the resulting big increase in the testdata tar size, but I can’t really think of an alternative.

**Comment by apontzen** [comment]
I added the file but it looks like the path isn't yet correct in the test suite

**Comment by Martin-Rey** [comment]
pre-commit.ci autofix

**Comment by apontzen** [comment]
Regarding the outstanding matter of general vs format-specific logic: I agree on both fronts that it would be better if generalised, but I prefer not to make potentially breaking changes unless we have a lot of time to test the potential implications.

Everything else looks fine to me so I am happy to merge this if you agree it's ready?

**Comment by Martin-Rey** [comment]
Sounds good, please go ahead and merge

**Pull request merged**
