### PR TITLE
Percentile profiles

### PR DESCRIPTION
**Pull request by jakobherpich**
For any simulation quantity `qty` (e.g. self defined values using `@pynbody.derived_array`), this pull request introduces the possibility to calculate the percentile of the respective quantity for every bin by invoking `prof['qyt_percentile50']`. This particular case returns the median. The general syntax is the quantity name followed by `"_percentile"` and any string representation of the percentage, e.g. '12.5', '16', '2e1' as long as the respective number is in the range 0...100.
```
prof = pynbody.analysis.profile.Profile(sim)
prof['vphi_percentile16.5']
```

### CODE REVIEW

**Comment by apontzen** [comment]
This is a very nice facility... Could you add an example in one of the tutorials and/or a test? That would round it off nicely!

**Comment by jakobherpich** [comment]
While adding an example to the tutorials, I realized that this feature has already been implemented in the `profile.QuantileProfile` class.

**Comment by rokroskar** [comment]
yes this was added by @stinsong4100 a long time ago -- I guess documentation was never created for it. Would be useful to do so now @jakobherpich?

**Comment by rokroskar** [comment]
hey @jakobherpich any chance to finish this off by adding documentation for the percentile profiles?

**Comment by apontzen** [comment]
This appears to be abandoned; I'm closing the PR now.

**Pull request closed without merging**
