### PR TITLE
dealing with star particle ages in ramses when proper time is used

### PR DESCRIPTION
**Pull request by mkrets**
When `use_proper_time=.true.` is used in a cosmological ramses simulation the formation time of star particles is saved in proper time. Namely there is no need to convert them (through `ramses_util.get_tform`).
The original issue is  #559 where I also explain the code-snippet.

To enable  the proper_time handling,  I add in the config .pynbodyrc:

```
[ramses]
proper_time: True
...
```

I had to add an ugly try/except block because python 2.7 doesnt support the fallback option in `config_parser.getboolean`.

I still need to add birth_time: tform as well.

```
[ramses-name-mapping]
position_x: x
position_y: y
...
birth_time: tform

...
```

and for the particle-blocks I also use tform
```
particle-blocks=x,y,z,vx,vy,vz,mass,iord,level,tform,metal
```

Alternatively `use_proper_time=.true.` could be directly read from the namelist (e.g. through #534 )

### CODE REVIEW

**Comment by apontzen** [comment]
Thanks! @Martin-Rey could you confirm this looks good to you? If so I am happy to merge.

**Comment by Martin-Rey** [comment]
Hi @mkrets,

Thanks a lot, this looks very good. Could you add the proper time flag in the default pynbody config file of the repository (https://github.com/pynbody/pynbody/blob/0b63e9be4aa34c6577f37bbd18f2261c2b2f0336/pynbody/default_config.ini#L170), with a line explanation such as:
```
# Use proper time when reading the age of star particles. 
# Should be turned to true if e.g. the namelist flag (use_proper_time) or radiative transfer have been used
proper_time: false
``` 

It would probably be good to implement a test catching this behaviour in the future, which should be fairly straightforward. There is an RT example run in the tesdata, so one could imagine turning the new `proper_time` flag on before loading the RT test (https://github.com/pynbody/pynbody/blob/0b63e9be4aa34c6577f37bbd18f2261c2b2f0336/nose/ramses_test.py#L72-L73) and adding an additional verification that the `tform` arrays produced are what we would expect. I am just to sure how you would modify the config file at runtime, any ideas @mkrets  and @apontzen ?

Martin

**Comment by mkrets** [comment]
Thanks for the replies.
I added the flag to the default config.

I agree a test would be good but yes one would have to switch the flag during runtime. I am not sure if that is possible. I looked at the `testdata/ramses_rt_partial_output_00002` but it seems that it does not contain stars.

One thing that confuses me is that I have to add:
```
[ramses-name-mapping]
birth_time: tform
```
Otherwise I get:
```python
ValueError: 'tform' is not in list
```
Should this also be in the default config?

**Comment by Martin-Rey** [comment]
Ah that's annoying to have to add additional data for the test. Let's see what @apontzen prefers and whether it is possible to change such config at runtimes?

Re- birth time: Pynbody tries to guess the name of particle fields from the header file (`output_00XXX/header.txt`) if I recall correctly. Is it possible that your header uses birth_time (which is the internal Ramses name) as the "name" of the `tform` array, hence why you have to remap it? 

If birth_time has become the default name for this array with the new Ramses format, yes it might worth adding as the default config.

**Comment by apontzen** [comment]
There isn't a nice way to do this, but you could probably have the test code change the appropriate variable in `pynbody.snapshot.ramses`. Not pretty, but better than leaving it untested I suspect.

**Comment by mkrets** [comment]
@Martin-Rey I checked and pynbody tries to load the particle field names from the `part_file_descriptor.txt` if that fails pynbody tries to guess it from the `header.txt.`

By default ramses writes `"birth_time"` in `part_file_descriptor.txt` : [see here](https://bitbucket.org/rteyssie/ramses/src/3e75d1ced915d53ca27cbab730282434ca2428b9/pm/output_part.f90#lines-167)

But `'tform'` in `header.txt` : [see here](https://bitbucket.org/rteyssie/ramses/src/3e75d1ced915d53ca27cbab730282434ca2428b9/amr/output_amr.f90#lines-542)

I propose adding `birth_time: tform` to `[ramses-name-mapping]`

**Comment by Martin-Rey** [comment]
@mkrets That makes sense to me. `tform` must be the historical name, that has been replaced by `birth_time` in the latest Ramses iteration. I agree it would be good to have this mapping done by default.

If you can manage to design a test using a small RT (or proper time) snapshot (for example using only 2-3 cpus of a bigger sim), it would be great. To enable testing, we could store the result of detecting proper time into a protected member (e.g. `self._is_using_proper_time`) of the `RamsesSnap` class, rather than the local variable `is_proper_time`. This member can then be accessed (and modified) at runtime, but only for users that know what to look for?

**Comment by mkrets** [comment]
I added a test. A small test output can be found here:

https://www.ics.uzh.ch/~mkretsch/prop_time_output_00030.tar.gz

**Comment by Martin-Rey** [comment]
Many thanks! @apontzen, could you add it to the testdata and re-run the travis build?

**Comment by mkrets** [comment]
I just noticed that ramses writes "metallicity" as the field name for metals in `part_file_descriptor.txt`  ([here](https://bitbucket.org/rteyssie/ramses/src/3e75d1ced915d53ca27cbab730282434ca2428b9/pm/output_part.f90#lines-177)). So additionally I had to add 
```
metallicity: metal
```
to `[ramses-name-mapping]` in the config. Should this also be in the default config?
@apontzen did you have a chance to look at the testdata I uploaded?

**Comment by apontzen** [comment]
Sorry for the delay, I've added this to the tar and restarted the travis build

**Comment by Martin-Rey** [comment]
Thanks @apontzen, looks like the new tests have passed 

@mkrets I think the metallicity mapping should indeed be added to the default config file, but only if `metallicity` is the default field name in the ramses master branch (note that this remapping is now unrelated with your original problem of proper time). I think the default choice should rather be “metals” (with an s), as in
```
metallicity: metals
```

as this is the spelling expected by most analysis routine in pynbody (allowing to calculate luminosities, half-light radius etc), and is the reason for the hardcoded remappings introduced in PR #521 when using the old ramses format for particle fields.

**Comment by apontzen** [comment]
Just wanted to check in with you @mkrets and @Martin-Rey about whether this is ready to merge? As I understand it, there is still some residual question about the default name mappings?

**Comment by mkrets** [comment]
Good to go from my side.
The question wether to add `metallicity: metals`  to the default config is not directly related to this PR.

**Comment by apontzen** [comment]
Thanks to you both!

**Comment by earnric** [comment]
Just a note for those using RAMSES RT sims that store time as proper time.

Make sure you force pynbody to load the tform array (e.g. - len(snap.stars['tform']) ) BEOFRE manipulating the arrays. 

I need to ensure that snap.s returns only active star particles, and not RAMSES debris particles. This may not be the best way to do it, but I simply:

    snap.s = snap.s[snap.s['iord'] > 0]

However, if you do this BEFORE loading tform, this causes a mismatch in the length of the arrays! If you load after this statement the tform array will be LONGER than you other star particle arrays and the values won't match up.

**Pull request merged**
