### PR TITLE
Modernize and streamline HaloCatalogue class hierarchy

### PR DESCRIPTION
**Pull request by apontzen**
Work on tangos has revealed there are deep-seated issues with the way the halo catalogue system works, with a jumble of approaches and different interfaces.

I am using this opportunity to largely re-write the halo catalogue base class and adjust/simplify the child classes. This clearly comes with risks attached but a modernisation is necessary for tangos and hopefully good for everyone in the long run.

I will also use this opportunity to remove the ability to run halo finders, which was always rather scattergun and goes beyond the boundaries of pynbody's functionality elsewhere. (See #434, #726). 

Implementations to complete:

- [x] grp / amigagrp 
- [x] Adaptahop
- [x] AHF
- [x] hop
- [x] rockstar
- [x] subfind
- [x] subfindhdf

Refinements to make:

- [x] iord to fpos mapping is probably better implemented as a clear class hierarchy, rather than pretending to always be an array. It needs better clarity e.g. over retaining ordering, and possibly profiling to see whether it is more efficient to use `numpy.searchsorted` [completed except for profiling which can be tackled if needed another time]
- [x] with clearer iord to fpos mapping, do an audit of where this is used in the codebase, and when it is applied to the whole catalogue vs to single halos
- [x] The `sub` mechanism implemented in subfindhdf should be clarified and extended to other relevant cases
- [x] tracking subclasses of HaloCatalogue should be automated, removing the need for a manually maintained list
- [x] users should be able to pass their own class priority list to `SimSnap.halos`, overriding the config-determined ordering
- [x] method naming and typing of the protected members of `HaloCatalogue` should be reviewed

Question: can we remove the `halo.legacy` module (@mtremmel ?)

### CODE REVIEW

**Comment by apontzen** [comment]
Additional question for @mtremmel 

It seems to me like when AHF halos are loaded currently, their ID value (if specified in the AHF halos file) is essentially ignored. If I am understanding correctly, this has led to a lot of heartache with tangos.

One possibility is that we actually start using the AHF-provided ID value in pynbody, rather than assuming just that the IDs are 1...N. Would this be a welcome change? 

I am not actually clear why/when AHF generates IDs that are not sequential. It's obviously a breaking change and it would perhaps be necessary to introduce it as an option to start with, and over a couple of years switch it to being the default option.

Thoughts very welcome (also @EthTay and @cphyc who I know have played with AHF considerably)

**Comment by apontzen** [comment]
Thanks for the explanation @mtremmel .

The problem we have at the moment is the different halo loaders in pynbody behave very differently, but if we expose more of this to the user and make things work similarly under the hood we should be ok.

I'm working on it, in a way that will break as little as possible ;-)

**Comment by apontzen** [comment]
There is a linked problem which is... why on earth do we start numbering things at 1, not 0? I am guessing this is some throwback to alyson's IDL tools. But even in the test data file (g15784), AHF seems implicitly itself to number things starting at zero.

**Comment by mtremmel** [comment]
Yeah... I think this is just tradition to be honest...

**Pull request merged**
