### PR TITLE
Fixes issue #375

### PR DESCRIPTION
**Pull request by jakobherpich**
Replaces PR #376 
The false binning in the calculation of Fourier components is fixed here.

### CODE REVIEW

**Comment by rokroskar** [comment]
actually changing from distutils to setuptools might not be appropriate here... @apontzen do you have an opinion on this? I just like being able to use `python setup.py develop` which you can't do with distutils...

**Comment by apontzen** [comment]
No major objections but I have always shied away from it, worried that setuptools is not standard. But it seems very rare to find a setup where it is not available any more.

**Comment by rokroskar** [comment]
oops looks like my test fails -- looks like `phi` is actually off by a factor of 2, not sure why at the moment.  I'll try to have a look later.

**Comment by jakobherpich** [comment]
@rokroskar That is expected. `phi` is `m` times the actual angle of the pattern so you'll have to divide the bar speed by m=2.

**Comment by rokroskar** [comment]
doh! I shouldn't do these things late on Friday...

**Comment by rokroskar** [comment]
@apontzen re: distutils vs. setuptools -- should I keep the change in here and merge? I can also undo it if you prefer to stay with distutils.

**Comment by apontzen** [comment]
Thanks both!

**Pull request merged**
