### PR TITLE
Add Colab Button to example notebook

### LINKED ISSUE #638: [Feature Request] Add Colab button to example notebook
I noticed that the [**`pynbody_demo`**](https://github.com/pynbody/pynbody/blob/master/examples/pynbody_demo.ipynb) notebook doesn't have a "Open in Colab" button and has a ValueError. Having the button would make experimentation extremely easy.

More than happy to take this up.

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Fixes #638 
---

This PR aims to add an "**Open in Colab**" Button to the [example notebook](https://github.com/SauravMaheshkar/pynbody/blob/master/examples/pynbody_demo.ipynb)

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
Request for Review @apontzen

**Comment by apontzen** [comment]
Thanks, wouldn't it also make sense to add a line to fetch and unpack the data? As it stands, it's still not possible to just play with this in colab without having to interpret the instructions and add extra lines manually.

**Comment by SauravMaheshkar** [comment]
Hey @apontzen sorry for the delay, I've added a snippet to download the data within the notebook.

**Comment by SauravMaheshkar** [comment]
@apontzen, Request for Review

**Comment by apontzen** [comment]
This PR is not currently mergeable due to changes on main since you branched.

I think you may need to start from the current main branch and add your cells. You can then force push here (or open a fresh pull request).

**Comment by SauravMaheshkar** [comment]
This should work right ?

**Comment by apontzen** [comment]
The notebook no longer renders -- I think the merge has produced an invalid notebook file. It's very hard to merge .ipynb manually. My suggestion would be to start afresh from the current main branch, pasting in the new cells, and force push a new version.

**Pull request closed without merging**
